cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask-fonts"

brew "git"
brew "tmux"
brew "anyenv"
brew "ruby-build"
brew "libyaml"
brew "docker"
brew "imagemagick"
brew "git"
brew "jq"
brew "bat"
brew "tree"
brew "wget"
brew "ghq"
brew "llvm"
brew "rustup-init"
brew "starship"
brew "zplug"
brew "cmake"
brew "ripgrep"
brew "peco"
brew "lazygit"

cask "appcleaner"
cask "clipy"
cask "discord"
cask "google-chrome"
cask "kindle"
cask "slack"
cask "visual-studio-code"
cask "1password"
cask "cmd-eikana"
cask "karabiner-elements"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "wezterm"
